### ISSUE TITLE
Run dependency-based SRL

### ISSUE THREAD

**Issue by alirezamshi-zz** [Riccorl/transformer-srl#3]
Hello, thanks for your bert-based implementation of SRL. 

Can you please provide the script for running the code on dependency-based SRL (ConLL 2009)? and is there any pretrained model? Thanks

**Comment by Riccorl** [comment]
Now there is a jsonnet in the `training_config` folder, called `bert_ml_conll2009.jsonnet` that can train with conll 2009 files (you can change the parameters here as you like). The reader assumes that the dataset is in one file, like

```
data/conll2009/train.txt
data/conll2009/dev.txt
```

I don't have the original dataset any more, I don't remember if it is distributed in small separated files, like conll 2012, or in one aggregated file. Anyway, if you feel the need to change that behaviour, the code is [here](https://github.com/Riccorl/transformer-srl/blob/master/transformer_srl/dataset_readers.py#L437).

A note about conll 2009. I never validate that dataset, so I'm not sure about performance and/or bugs. I didn't implement the official score for it yet. I accept suggestions in that regard since I didn't have time to study how the official evaluation script works. It shouldn't be hard btw.

> and is there any pretrained model?

I don't have pre-trained model with conll 2009 and PropBank, sorry about that.
